/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ChangePasswordRequest;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApiServiceApi
 */
@Ignore
public class UserApiServiceApiTest {

    private final UserApiServiceApi api = new UserApiServiceApi();

    /**
     * Cambio de contraseña
     *
     * Método para cambiar la contraseña del usuario
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void changePasswordTest() throws Exception {
        ChangePasswordRequest body = null;
        api.changePassword(body);

        // TODO: test validations
    }
    /**
     * Creacion  de usuarios
     *
     * Crear un usuario
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crearTest() throws Exception {
        Object body = null;
        User response = api.crear(body);

        // TODO: test validations
    }
    /**
     * Solicitar usuario
     *
     * Método para comprobar un usuario por id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getByIdTest() throws Exception {
        Object idUser = null;
        User response = api.getById(idUser);

        // TODO: test validations
    }
    /**
     * Login de usuario
     *
     * Método para que el usuario haga login con su contraseña y usuario.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws Exception {
        Object username = null;
        Object password = null;
        User response = api.login(username, password);

        // TODO: test validations
    }
}
