/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Cliente;
import org.openapitools.client.model.CreateClientRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientApiServiceApi
 */
@Disabled
public class ClientApiServiceApiTest {

    private final ClientApiServiceApi api = new ClientApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void actualizeClientTest() throws ApiException {
        CreateClientRequest createClientRequest = null;
        Cliente response = api.actualizeClient(createClientRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkClientDniTest() throws ApiException {
        String dni = null;
        Cliente response = api.checkClientDni(dni);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkClientIdTest() throws ApiException {
        String id = null;
        Cliente response = api.checkClientId(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createClientTest() throws ApiException {
        CreateClientRequest createClientRequest = null;
        Cliente response = api.createClient(createClientRequest);
        // TODO: test validations
    }

}
