/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.time.LocalDate;
import org.openapitools.client.model.Pedido;
import org.openapitools.client.model.PedidoDetalle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PedidoApiServiceApi
 */
@Disabled
public class PedidoApiServiceApiTest {

    private final PedidoApiServiceApi api = new PedidoApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addDetalleTest() throws ApiException {
        String id = null;
        PedidoDetalle pedidoDetalle = null;
        Pedido response = api.addDetalle(id, pedidoDetalle);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPedidoDniTest() throws ApiException {
        String dni = null;
        List<Pedido> response = api.buscarPedidoDni(dni);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPedidoFechaTest() throws ApiException {
        LocalDate antes = null;
        LocalDate despues = null;
        List<Pedido> response = api.buscarPedidoFecha(antes, despues);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarPedidoTest() throws ApiException {
        String id = null;
        Pedido response = api.consultarPedido(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registrarPedidoTest() throws ApiException {
        Pedido pedido = null;
        String response = api.registrarPedido(pedido);
        // TODO: test validations
    }

}
